library(shiny)
library(leaflet)
library(leaflet.extras)
library(scales)
library(shinycssloaders)
library(sf)
library(raster)
library(htmltools)
library(rgdal)
library(dplyr)
library(zoo)
library(rowr)
library(precintcon)
library(gridExtra)
library(fitdistrplus)
library(tictoc)
library(ncdf4) 
library(lubridate)
library(plotly)

#SPI data
current_spi_30 = raster::raster("../spi_app/maps/current_spi/current_spi_30.tif")
current_spi_60 = raster::raster("../spi_app/maps/current_spi/current_spi_60.tif")
current_spi_90 = raster::raster("../spi_app/maps/current_spi/current_spi_90.tif")
current_spi_180 = raster::raster("../spi_app/maps/current_spi/current_spi_180.tif")
current_spi_300 = raster::raster("../spi_app/maps/current_spi/current_spi_300.tif")

watersheds_30 = st_read("../spi_app/shp/current_spi/current_spi_watershed_30.shp")
watersheds_60 = st_read("../spi_app/shp/current_spi/current_spi_watershed_60.shp")
watersheds_90 = st_read("../spi_app/shp/current_spi/current_spi_watershed_90.shp")
watersheds_180 = st_read("../spi_app/shp/current_spi/current_spi_watershed_180.shp")
watersheds_300 = st_read("../spi_app/shp/current_spi/current_spi_watershed_300.shp")

county_30 = st_read("../spi_app/shp/current_spi/current_spi_county_30.shp")
county_60 = st_read("../spi_app/shp/current_spi/current_spi_county_60.shp")
county_90 = st_read("../spi_app/shp/current_spi/current_spi_county_90.shp")
county_180 = st_read("../spi_app/shp/current_spi/current_spi_county_180.shp")
county_300 = st_read("../spi_app/shp/current_spi/current_spi_county_300.shp")

#SPEI Data
current_spei_30 = raster::raster("../spei_app/maps/current_spei/current_spei_30.tif")
current_spei_60 = raster::raster("../spei_app/maps/current_spei/current_spei_60.tif")
current_spei_90 = raster::raster("../spei_app/maps/current_spei/current_spei_90.tif")
current_spei_180 = raster::raster("../spei_app/maps/current_spei/current_spei_180.tif")
current_spei_300 = raster::raster("../spei_app/maps/current_spei/current_spei_300.tif")

watersheds_30 = st_read("../spei_app/shp/current_spei/current_spei_watershed_30.shp")
watersheds_60 = st_read("../spei_app/shp/current_spei/current_spei_watershed_60.shp")
watersheds_90 = st_read("../spei_app/shp/current_spei/current_spei_watershed_90.shp")
watersheds_180 = st_read("../spei_app/shp/current_spei/current_spei_watershed_180.shp")
watersheds_300 = st_read("../spei_app/shp/current_spei/current_spei_watershed_300.shp")

county_30 = st_read("../spei_app/shp/current_spei/current_spei_county_30.shp")
county_60 = st_read("../spei_app/shp/current_spei/current_spei_county_60.shp")
county_90 = st_read("../spei_app/shp/current_spei/current_spei_county_90.shp")
county_180 = st_read("../spei_app/shp/current_spei/current_spei_county_180.shp")
county_300 = st_read("../spei_app/shp/current_spei/current_spei_county_300.shp")